version: "3"
services:
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
    - "3000:3000"
  nginx:
    depends_on:
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./src/nginx
    ports:
    - "80:80"